user nobody nobody;
worker_processes auto;

events
{
  worker_connections 65535;
}

http
{
  default_type application/octet-stream;

  server
  {
    listen 80;

    include /etc/nginx/conf.d/feishin.conf;
    include /etc/nginx/conf.d/chord.conf;
  }
}
